package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var types = flag.String("type", "", "target type")

func filter(file os.FileInfo) bool {
	if filepath.Ext(file.Name()) == ".go" {
		if !strings.Contains(file.Name(), "generated") {
			return true
		}
	}
	return false
}

func main() {
	flag.Parse()
	if len(*types) == 0 {
		log.Fatalln("Please set types")
		return
	}
	//typeList := strings.Split(*types, ",")
	fset := token.NewFileSet()
	asts, err := parser.ParseDir(fset, ".", filter, 0)
	mem := ""
	if err != nil {
		log.Fatal(err)
		return
	}
	var constList []string
	pkgName := ""
	for pName, astTree := range asts {
		pkgName = pName
		for _, file := range astTree.Files {
			for _, obj := range file.Decls {
				if con, ok := obj.(*ast.GenDecl); ok {
					if con.Tok == token.CONST {
						for _, decl := range con.Specs {
							if value, ok := decl.(*ast.ValueSpec); ok {
								if value.Type == nil && len(value.Values) > 0 {
									mem = ""
									continue
								}
								if value.Type != nil {
									if ident, ok := value.Type.(*ast.Ident); ok {
										fmt.Println(ident.String())
										mem = ident.Name
									}
								}
								if mem == *types {
									constList = append(constList, value.Names[0].Name)
								}
							}
						}
					}
				}
			}
		}
	}
	gen, err := os.Create(strings.ToLower(*types) + "_makeerror.go")
	if err != nil {
		log.Fatal(err)
		return
	}
	defer gen.Close()
	fmt.Fprintf(gen, "//This file generated by makeerror DO NOT CHANGE!\n")
	fmt.Fprintf(gen, "package %v\n\n", pkgName)
	fmt.Fprintf(gen, "const (\n")
	for _, c := range constList {
		fmt.Fprintf(gen, "\tstr%v = \"%[1]v\"\n", c)
	}
	fmt.Fprintf(gen, "\tmakeerrorUnknown = \"Unknown error type\"\n")
	fmt.Fprintf(gen, ")\n\n")
	abbrType := string(strings.ToLower(*types)[0])
	fmt.Fprintf(gen, "func (%v %v) Error() string{\n", abbrType, *types)
	fmt.Fprintf(gen, "\tswitch %v {\n", abbrType)
	for _, c := range constList {
		fmt.Fprintf(gen, "\t\tcase %v: return str%[1]v\n", c)
	}
	fmt.Fprintf(gen, "\t}\n")
	fmt.Fprintf(gen, "\treturn makeerrorUnknown\n")
	fmt.Fprintf(gen, "}\n")
}
